### ISSUE TITLE
hello, I hava a question in paper!

### ISSUE THREAD

**Issue by Xiaoccer** [menoRashid/animal_human_kp#1]
What's the meaning about 'use a 5×5 grid of control points'? Is it about the grid generator in the warping Network?

**Comment by menorashid** [comment]
Hi! To do a tps transformation, you have a set of control points that form an evenly spaced between -1 and 1.  The stn predicts offsets for these control points, and then the offsets are used to warp all the points in the image using the spline defined by the control points. 

This link has visualizations of the control pts:
https://github.com/WarBean/tps_stn_pytorch

and Warpnet's supplementary has more mathematical detail:
http://people.eecs.berkeley.edu/~kanazawa/papers/kanazawa_cvpr2016_warpnet_supplementary.pdf

**Comment by Xiaoccer** [comment]
Thank you very much ! I think your work is so interesting ! Thanks for your sharing !
