### ISSUE TITLE
horse dataset url is unavailable

### ISSUE THREAD

**Issue by niaoyu** [menoRashid/animal_human_kp#4]
Thanks for your nice work!
I just wonder the horse dataset url is not working, 
 could you just update a correct one?

**Comment by menorashid** [comment]
the link is working fine for me. 
https://www.dropbox.com/s/9t770jhcjqo3mmg/release_data.zip

If you send me an email, I can email you the dataset. Sorry for the late reply. I don't check issues. email is best.

**Comment by n3ry7** [comment]
It is not working here, can I e-mail you?
